name: Build, Test and Deploy to Vercel
on:
  push:
    branches:
      - main
jobs:
  Install_dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
        working-directory: frontend

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: npm run build
        working-directory: frontend

  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: npm test
        working-directory: frontend

  deploy_to_vercel:
    runs-on: ubuntu-latest
    steps:
      - name: Install Vercel CLI
        run: npm i -g vercel
      - name: Deploy to Vercel
        run: vercel deploy --prod --yes --token ${{ secrets.VERCEL_TOKEN }}
